### PR TITLE
chore: fix wpt output

### LINKED ISSUE #2460: WPT test failures are not reported
Run `VERBOSE=true CHROMEDRIVER=false npm run wpt -- webdriver/tests/bidi/session` and have some test failures. 

Server logs are in the logs folder but no report about which tests were run and failed is present.

### PR DESCRIPTION
**Pull request by Lightning00Blade**
Closes #2460

### CODE REVIEW

**Review by OrKoN — APPROVED** [review]

File: tools/run-wpt.mjs [hunk 1]
```diff
@@ -244,9 +244,31 @@ if (RUN_TESTS === 'true') {
...
+    output += data.toString();
+  });
+
+  wptRun.stderr.setEncoding('utf8');
+  wptRun.stderr.pipe(process.stderr);
+  wptRun.stderr.on('data', (data) => {
+    output += data.toString();
+  });
+
+  wptRun.on('exit', (status) => {
```
Comment (OrKoN) [inline tools/run-wpt.mjs:266]: you should also probably listen to the error event

**Review by OrKoN — APPROVED** [review]
